version: "3"

tasks:
  test:
    desc: "Run all tests with verbose output"
    cmds:
      - go test ./... -v

  coverage:
    desc: "Run tests and show code coverage summary"
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -func=coverage.out

  coverhtml:
    desc: "Run tests and open HTML coverage report"
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -html=coverage.out

  clean:
    desc: "Remove coverage output"
    cmds:
      - rm -f coverage.out
